import { Link } from 'react-router-dom';
import { Shield, Calendar } from 'lucide-react';

interface EEATDisclosureProps {
  lastUpdated: string;
}

/**
 * E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) Disclosure
 * Critical for YMYL (Your Money Your Life) pages like financial content.
 * Helps search engines understand the credibility and data sourcing of the content.
 */
export function EEATDisclosure({ lastUpdated }: EEATDisclosureProps) {
  return (
    <aside className="bg-muted/50 p-4 rounded-lg text-sm border border-border/50">
      <div className="flex items-start gap-3">
        <Shield className="h-5 w-5 text-primary flex-shrink-0 mt-0.5" />
        <div className="space-y-2">
          <p className="text-foreground">
            This analysis is generated by <strong>ClaritX</strong>, an AI-powered stock research 
            platform using multi-angle analysis methodology. Data is sourced from Financial Modeling 
            Prep, verified market feeds, and real-time news aggregation.
          </p>
          <div className="flex items-center gap-4 text-muted-foreground">
            <span className="flex items-center gap-1">
              <Calendar className="h-4 w-4" />
              Last updated: {lastUpdated}
            </span>
          </div>
          <p className="text-xs text-muted-foreground mt-2">
            <strong>Disclaimer:</strong> This is not investment advice. ClaritX provides educational 
            research tools only. Past performance does not guarantee future results. All investments 
            carry risk of loss. Always consult a licensed financial advisor before making investment 
            decisions.{' '}
            <Link to="/disclaimer" className="text-primary hover:underline">
              Read full disclaimer
            </Link>.
          </p>
        </div>
      </div>
    </aside>
  );
}
