CREATE TABLE IF NOT EXISTS chat_jobs (
    id UUID PRIMARY KEY,
    status VARCHAR(50) NOT NULL DEFAULT 'running',
    content TEXT,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
