import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { AlertTriangle, Info, Shield, TrendingDown, Users, Globe, Scale, Coins } from "lucide-react";
import { SEOHead, BreadcrumbSchema } from "@/components/SEOHead";

const Disclaimer = () => {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <SEOHead
        title="Disclaimer | Investment Risk Disclosures | ClaritX"
        description="Important disclaimer and risk disclosures for ClaritX. Our AI-powered stock analysis is for educational purposes only and does not constitute investment advice."
        keywords="disclaimer, investment disclaimer, risk disclosure, financial disclaimer, not investment advice"
        canonicalUrl="/disclaimer"
      />
      <BreadcrumbSchema
        items={[
          { name: "Home", url: "/" },
          { name: "Disclaimer", url: "/disclaimer" }
        ]}
      />
      <Header />
      <main className="container mx-auto px-4 pt-24 pb-16 flex-1">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-display font-bold text-foreground mb-4">Important Disclaimer & Disclosures</h1>
          <p className="text-muted-foreground mb-8">Please read this disclaimer carefully before using ClaritX. Last updated: April 14, 2026</p>

          {/* Key Warning Box */}
          <div className="glass-card p-6 mb-8 border-l-4 border-destructive bg-destructive/5">
            <div className="flex items-start gap-4">
              <AlertTriangle className="h-8 w-8 text-destructive flex-shrink-0 mt-1" />
              <div>
                <h2 className="text-xl font-semibold text-foreground mb-2">NOT INVESTMENT ADVICE</h2>
                <p className="text-muted-foreground leading-relaxed">
                  ClaritX provides market data and automated analysis for <strong>educational and informational purposes only</strong>. 
                  Nothing on this platform constitutes personalized investment advice, a recommendation to buy or sell any security, 
                  or an offer to provide investment advisory services. All content is impersonal and generated by automated systems 
                  without consideration of your individual financial circumstances, investment objectives, or risk tolerance.
                </p>
              </div>
            </div>
          </div>

          {/* Core Disclaimers */}
          <div className="grid md:grid-cols-2 gap-6 mb-8">
            <div className="glass-card p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-primary/20 flex items-center justify-center">
                  <Scale className="h-5 w-5 text-primary" />
                </div>
                <h3 className="font-semibold text-foreground">No Advisory Relationship</h3>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                Using ClaritX does not create any investment adviser-client relationship or fiduciary duty. 
                ClaritX is <strong>not a registered investment adviser</strong>, broker-dealer, or financial planner. 
                We are not regulated by the SEC, FINRA, FCA, ESMA, or any other financial regulatory authority. 
                Our service falls under the publisher's exclusion for bona fide financial publications.
              </p>
            </div>

            <div className="glass-card p-6">
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-secondary/20 flex items-center justify-center">
                  <Shield className="h-5 w-5 text-secondary" />
                </div>
                <h3 className="font-semibold text-foreground">No Recommendations</h3>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                All analyses are <strong>impersonal and general in nature</strong>. Nothing on this platform should be construed 
                as a recommendation to buy, sell, or hold any security or a solicitation of any transaction. 
                "Bullish" and "Bearish" signals reflect automated pattern analysis, not advice on whether 
                any particular investment is suitable for you.
              </p>
            </div>
          </div>

          {/* Risk Warnings */}
          <div className="glass-card p-6 mb-8 border-l-4 border-destructive bg-destructive/5">
            <div className="flex items-start gap-4">
              <TrendingDown className="h-8 w-8 text-destructive flex-shrink-0 mt-1" />
              <div>
                <h2 className="text-xl font-semibold text-foreground mb-3">Investment Risk Warnings</h2>
                <ul className="space-y-3 text-muted-foreground">
                  <li className="flex items-start gap-2">
                    <span className="text-destructive font-bold">•</span>
                    <span><strong>Capital at Risk:</strong> The value of investments can go down as well as up. You may lose some or all of your invested capital.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-destructive font-bold">•</span>
                    <span><strong>Past Performance:</strong> Past performance, whether actual or simulated, is not a reliable indicator of future results.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-destructive font-bold">•</span>
                    <span><strong>Hypothetical Results:</strong> Any simulated portfolios or backtested results have inherent limitations and do not represent actual trading.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-destructive font-bold">•</span>
                    <span><strong>Only Risk Capital:</strong> Do not invest money you cannot afford to lose. Consider your overall financial situation before investing.</span>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          {/* Detailed Sections */}
          <div className="space-y-8">
            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4 flex items-center gap-2">
                <Info className="h-6 w-6 text-primary" />
                Do Your Own Research
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                It is essential that you conduct your own independent analysis or consult a qualified, licensed financial 
                advisor before making any investment decisions. Do not rely solely on ClaritX's output when investing. 
                You should independently research and verify any information from this platform and consider your complete 
                financial situation, investment objectives, and risk tolerance before acting on any information.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Automated Analysis Limitations</h2>
              <p className="text-muted-foreground leading-relaxed mb-4">
                ClaritX uses automated algorithms to analyze publicly available market data. These algorithms identify 
                patterns in historical data; <strong>they cannot predict the future with any certainty</strong>. 
                Market conditions can change rapidly, and automated analysis may not account for breaking news, 
                geopolitical events, or other unpredictable factors that can significantly impact security prices.
              </p>
              <p className="text-muted-foreground leading-relaxed">
                While we strive to ensure data accuracy, we do not guarantee the correctness, completeness, or timeliness 
                of any information. Stock quotes may be delayed. Third-party data sources may contain errors or omissions. 
                We are not responsible for decisions made based on any inaccuracies in the data.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">MiFID II Risk Profile Disclaimer</h2>
              <p className="text-muted-foreground leading-relaxed">
                ClaritX features a risk profiling questionnaire designed to follow MiFID II guidelines for educational 
                purposes. However, this questionnaire is used only to generate sample portfolio illustrations and 
                <strong> does not constitute a tailored investment recommendation or suitability assessment</strong>. 
                No suitability determination (as required for regulated investment advice under MiFID II, Article 25) 
                is being performed. You remain solely responsible for determining if any investment is suitable for 
                your personal circumstances. We encourage you to seek professional advice for a comprehensive suitability analysis.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4 flex items-center gap-2">
                <Coins className="h-6 w-6 text-primary" />
                Affiliate Disclosure
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                ClaritX may receive compensation from broker partners if you sign up for an account or execute trades 
                through referral links on this platform. This compensation does not influence our automated analysis 
                or the content we provide. We disclose this relationship for transparency. Any broker links are provided 
                for user convenience only; ClaritX does not endorse any particular broker and is not involved in the 
                execution of any trades. All trading is conducted at your own risk through your chosen broker.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Limitation of Liability</h2>
              <p className="text-muted-foreground leading-relaxed">
                To the maximum extent permitted by applicable law, ClaritX and its affiliates, officers, directors, 
                employees, and agents shall not be liable for any loss or damage arising from any use of or reliance 
                on the information provided on this platform. This includes, without limitation, any direct, indirect, 
                incidental, consequential, special, or punitive damages resulting from investment decisions based on 
                our analysis, data inaccuracies, service interruptions, or any other use of our platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4">Conflicts of Interest</h2>
              <p className="text-muted-foreground leading-relaxed">
                ClaritX, its affiliates, and its employees may hold positions in securities that are analyzed on 
                this platform. Our automated analysis is generated independently without consideration of any 
                positions we may hold. We do not engage in front-running or market manipulation. For transparency, 
                assume that we or our affiliates may have financial interests in securities mentioned on this platform.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4 flex items-center gap-2">
                <Globe className="h-6 w-6 text-primary" />
                Geographic and Age Restrictions
              </h2>
              <p className="text-muted-foreground leading-relaxed">
                The content of this platform is not intended for distribution to, or use by, any person or entity in 
                any jurisdiction where such distribution or use would violate local laws or regulations, or where we 
                would be subject to any registration requirement. It is your responsibility to ensure that accessing 
                and using ClaritX is legal in your jurisdiction. This service is intended for users who are at least 
                18 years of age (or the age of majority in your jurisdiction).
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold text-foreground mb-4 flex items-center gap-2">
                <Users className="h-6 w-6 text-primary" />
                Regulatory Framework Reference
              </h2>
              <div className="text-muted-foreground leading-relaxed space-y-3">
                <p>
                  <strong>United States:</strong> ClaritX relies on the publisher's exclusion under Section 202(a)(11)(D) 
                  of the Investment Advisers Act of 1940 for bona fide publications of general circulation.
                </p>
                <p>
                  <strong>European Union:</strong> Per MiFID II (Directive 2014/65/EU) and the Delegated Regulation 
                  (EU) 2017/565, recommendations addressed exclusively to the public are not personal recommendations.
                </p>
                <p>
                  <strong>United Kingdom:</strong> Content is provided on an informational basis and is not intended 
                  as a financial promotion within the meaning of Section 21 of the Financial Services and Markets Act 2000.
                </p>
              </div>
            </section>
          </div>

          {/* Final Notice */}
          <div className="mt-12 p-6 rounded-lg bg-warning/10 border-2 border-warning/30 text-center">
            <AlertTriangle className="h-8 w-8 text-warning mx-auto mb-3" />
            <p className="text-foreground font-semibold mb-2">
              By using ClaritX, you acknowledge that you have read, understood, and agree to this Disclaimer.
            </p>
            <p className="text-muted-foreground text-sm">
              If you do not agree with any part of this disclaimer, please do not use the Service. 
              This disclaimer may be updated from time to time; continued use constitutes acceptance of any changes.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default Disclaimer;
