import { Link } from "react-router-dom";
import { TrendingUp, AlertTriangle, Info, Twitter, Linkedin } from "lucide-react";
import { useTheme } from "next-themes";

export const Footer = () => {
  const { resolvedTheme } = useTheme();
  
  return (
    <footer className="border-t border-border bg-muted/30">
      {/* Regulatory Disclaimer Banner */}
      <div className="bg-warning/10 border-b border-warning/20">
        <div className="container mx-auto px-4 py-3 sm:py-4">
          <div className="flex items-start gap-2 sm:gap-3 justify-center">
            <AlertTriangle className="h-4 w-4 sm:h-5 sm:w-5 text-warning flex-shrink-0 mt-0.5" />
            <div className="text-center max-w-4xl">
              <p className="text-[10px] sm:text-xs text-muted-foreground leading-relaxed">
                <strong className="text-warning">Important Disclosure:</strong> ClaritX provides market data and automated analysis for{" "}
                <strong>educational and informational purposes only</strong>. ClaritX is not a registered investment adviser, broker-dealer, 
                or financial planner. <span className="hidden sm:inline">Nothing on this platform constitutes personalized investment advice or a recommendation to buy or sell 
                any security. All analysis is impersonal and generated by automated systems. Past performance does not guarantee future results. 
                Investments involve risk and you may lose money.</span>{" "}
                <Link to="/disclaimer" className="text-primary hover:underline font-medium">
                  Read full disclaimer →
                </Link>
              </p>
            </div>
          </div>
        </div>
      </div>

      <div className="container mx-auto px-4 py-6 sm:py-8">
        <div className="grid grid-cols-2 md:grid-cols-5 gap-6 sm:gap-8">
          {/* Brand */}
          <div className="col-span-2 md:col-span-1 space-y-3 sm:space-y-4">
            <Link to="/" className="flex items-center">
              <div className="overflow-hidden h-8 sm:h-10">
                <img 
                  src={resolvedTheme !== 'light' ? '/logo-white.png' : '/logo-black.png'}
                  alt="ClaritX - AI Deep Research & Portfolio Research Platform"
                  width={80}
                  height={40}
                  className="h-16 sm:h-20 w-auto -mt-4 sm:-mt-5"
                />
              </div>
            </Link>
            <p className="text-xs sm:text-sm text-muted-foreground">
              AI-Powered Market Analysis & Research Tools
            </p>
            <p className="text-[10px] sm:text-xs text-muted-foreground">
              For Educational Purposes Only
            </p>
            {/* Social Links */}
            <div className="flex items-center gap-3 pt-2">
              <a
                href="https://x.com/Clarit_X"
                target="_blank"
                rel="noopener noreferrer"
                className="text-muted-foreground hover:text-primary transition-colors"
                aria-label="Follow ClaritX on X"
              >
                <Twitter className="h-4 w-4" />
              </a>
              <a
                href="https://www.linkedin.com/company/claritx-ai"
                target="_blank"
                rel="noopener noreferrer"
                className="text-muted-foreground hover:text-primary transition-colors"
                aria-label="Follow ClaritX on LinkedIn"
              >
                <Linkedin className="h-4 w-4" />
              </a>
            </div>
          </div>

          {/* Research Tools */}
          <div className="space-y-3 sm:space-y-4">
            <h3 className="font-semibold text-foreground text-sm sm:text-base">Research Tools</h3>
            <ul className="space-y-1.5 sm:space-y-2 text-xs sm:text-sm">
              <li>
                <Link to="/" className="text-muted-foreground hover:text-primary transition-colors">
                  Deep Research
                </Link>
              </li>
              <li>
                <Link to="/ai-stock-rank" className="text-muted-foreground hover:text-primary transition-colors">
                  AI Stock Rankings
                </Link>
              </li>
              <li>
                <Link to="/portfolio-simulator" className="text-muted-foreground hover:text-primary transition-colors">
                  Portfolio Simulator
                </Link>
              </li>
              <li>
                <Link to="/stocks" className="text-muted-foreground hover:text-primary transition-colors">
                  Browse Stocks
                </Link>
              </li>
              <li>
                <Link to="/pricing" className="text-muted-foreground hover:text-primary transition-colors font-medium text-primary">
                  Plans & Pricing
                </Link>
              </li>
            </ul>
          </div>

          {/* Learn */}
          <div className="space-y-3 sm:space-y-4">
            <h3 className="font-semibold text-foreground text-sm sm:text-base">Learn</h3>
            <ul className="space-y-1.5 sm:space-y-2 text-xs sm:text-sm">
              <li>
                <Link to="/blog" className="text-muted-foreground hover:text-primary transition-colors">
                  Investment Blog
                </Link>
              </li>
              <li>
                <Link to="/blog/how-to-analyze-stocks-complete-guide" className="text-muted-foreground hover:text-primary transition-colors">
                  How to Analyze Stocks
                </Link>
              </li>
              <li>
                <Link to="/blog/best-dividend-stocks-for-retirement" className="text-muted-foreground hover:text-primary transition-colors">
                  Dividend Investing
                </Link>
              </li>
              <li>
                <Link to="/blog/safe-stocks-for-beginners-low-risk" className="text-muted-foreground hover:text-primary transition-colors">
                  Beginner's Guide
                </Link>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div className="space-y-3 sm:space-y-4">
            <h3 className="font-semibold text-foreground text-sm sm:text-base">Legal</h3>
            <ul className="space-y-1.5 sm:space-y-2 text-xs sm:text-sm">
              <li>
                <Link to="/terms" className="text-muted-foreground hover:text-primary transition-colors">
                  Terms of Service
                </Link>
              </li>
              <li>
                <Link to="/disclaimer" className="text-muted-foreground hover:text-primary transition-colors">
                  Important Disclaimer
                </Link>
              </li>
              <li>
                <Link to="/privacy" className="text-muted-foreground hover:text-primary transition-colors">
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link to="/about" className="text-muted-foreground hover:text-primary transition-colors">
                  About ClaritX
                </Link>
              </li>
            </ul>
          </div>

          {/* Risk Warning */}
          <div className="col-span-2 md:col-span-1 space-y-3 sm:space-y-4">
            <h3 className="font-semibold text-foreground flex items-center gap-2 text-sm sm:text-base">
              <Info className="h-3 w-3 sm:h-4 sm:w-4" />
              Risk Warning
            </h3>
            <div className="text-[10px] sm:text-xs text-muted-foreground leading-relaxed space-y-1.5 sm:space-y-2">
              <p>
                <strong className="text-foreground">Investments can go down as well as up.</strong> You may lose some or all of your capital.
              </p>
              <p className="hidden sm:block">
                Past performance is not indicative of future results. This platform does not provide investment advice.
              </p>
              <p className="hidden sm:block">
                ClaritX may receive compensation from partner brokers. See our disclosure for details.
              </p>
            </div>
          </div>
        </div>

        {/* Bottom Bar */}
        <div className="mt-6 sm:mt-8 pt-4 sm:pt-6 border-t border-border">
          <div className="flex flex-col sm:flex-row justify-between items-center gap-3 sm:gap-4">
            <p className="text-[10px] sm:text-xs text-muted-foreground text-center sm:text-left">
              © {new Date().getFullYear()} ClaritX. All rights reserved. Not a registered investment adviser.
            </p>
            <p className="text-[10px] sm:text-xs text-muted-foreground text-center sm:text-right">
              By using this site, you acknowledge that all content is for{" "}
              <strong>educational purposes only</strong> and agree to our{" "}
              <Link to="/terms" className="text-primary hover:underline">Terms</Link>
              {" "}and{" "}
              <Link to="/disclaimer" className="text-primary hover:underline">Disclaimer</Link>.
            </p>
          </div>
        </div>
      </div>
    </footer>
  );
};
